apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: risingstackbootcamp-com-tls
spec:
  secretName: risingstackbootcamp-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: risingstackbootcamp.com
  dnsNames:
    - risingstackbootcamp.com
    - www.risingstackbootcamp.com
  acme:
    config:
      - http01:
        ingressClass: nginx

      - domains:
        - risingstackbootcamp.com
        - www.risingstackbootcamp.com
