apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: bootcamp-risingstack-com
spec:
  secretName: bootcamp-risingstack-com-tls
  issuerRef: 
    name: letsencrypt-prod
  commonName: bootcamp.risingstack.com
  dnsNames:
    - bootcamp.risingstack.com
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
        - risingstackbootcamp.com