apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: 'gulyas97@freemail.hu'
      privateKeySecretRef:
        name: letsencrypt-prod
      # http01:{}
      solvers:
        - http01:
            ingress:
              class: nginx